# Environment variables that must be set in Gitlab CI/CD Pipeline variables
# ALPINE_IMAGE
# CENTOS_IMAGE
# DOCKER_AUTH_CONFIG
# DOCKER_DEV_AUTH_CONFIG
# DOCKER_DEV_USER
# DOCKER_USER
# DOCKER_IMAGE
# DIND_IMAGE
# GOSU_URL
# LOGSTASH_IMAGE
# REGISTRY
# VAULT_ZIP

variables:
  IMAGE_PREFIX: "scale"
  EPEL_INSTALL: "0"

image: ${DOCKER_IMAGE}

services:
  - ${DIND_IMAGE}

stages:
  - package

logstash:
  stage: package
  script:
    - ./build-support.sh ${LOGSTASH_IMAGE} logstash
  only:
    - tags

scale:
  stage: package
  script:
    - ./build-scale.sh
  only:
    - master
    - tags

vault:
  stage: package
  script:
    - ./build-support.sh ${ALPINE_IMAGE} vault
  only:
    - tags
