language: python
env:
  global:
  - TRAVIS=1

python:
- '2.7'

services:
- postgresql

before_install:
- if [ "${TRAVIS_BRANCH}" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false"]; then openssl aes-256-cbc -K $encrypted_54e1fa350980_key -iv $encrypted_54e1fa350980_iv
  -in publish-key.enc -out ~/.ssh/publish-key -d; fi
before_script:
- cp scale/scale/local_settings_TRAVIS-CI.py scale/scale/local_settings.py
- psql -c 'create database scale;' -U postgres
- psql -d scale -U postgres -c "create extension postgis;"
- psql -d scale -U postgres -c "create extension postgis_topology;"
- python scale/manage.py migrate --noinput
# Add NodeJS 6 to build dependencies
- wget https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh -O ~/.nvm/nvm.sh
- source ~/.nvm/nvm.sh
- nvm install 6
install:
- pip install -q -r scale/pip/build_linux.txt
script: ./travis-build.sh

branches:
  only:
  - master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/11ff4f6760c5e218ccb7
    on_success: change
    on_failure: always
    on_start: never
