language: python

python:
- '2.7'

cache: packages
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

matrix:
  include:
    - os: linux
      env: RUN_TESTS='true'
      addons:
        postgresql: "9.5"
        apt:
          packages:
            - postgresql-9.5-postgis-2.3

    - os: linux
      env: BUILD_DOCS='true'
      
    - os: linux
      env: BUILD_DOCKER='true'
      sudo: required
      services: 
        - docker

cache: pip

# Travis team suggested fix for truncated log build failures
filter_secrets: false

install:
- if [ "${RUN_TESTS}" == "true" ]; then pip install -q -r scale/pip/requirements.txt; fi
- if [ "${BUILD_DOCS}" == "true" ]; then pip install -q -r scale/pip/docs.txt -r scale/pip/production.txt; fi

script: 
- ./travis-build.sh
- if [ "${BUILD_DOCKER}" == "true" ]; then docker build --build-arg BUILD_DOCS=0 .; fi
- if [ "${BUILD_DOCS}" == "true" ]; then ./push-docs.sh; fi

branches:
  only:
  - master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/11ff4f6760c5e218ccb7
    on_success: change
    on_failure: always
    on_start: never
