language: python

python:
- '2.7'

matrix:
  include:
    - os: linux
      env: RUN_TESTS='true'   BUILD_DOCS='false'
      addons:
        postgresql: "9.4"

    - os: linux
      env: RUN_TESTS='false'  BUILD_DOCS='true'

cache: pip

# Travis team suggested fix for truncated log build failures
filter_secrets: false

install:
- if [ ${RUN_TESTS} == 'true' ]; then pip install -q -r scale/pip/requirements.txt; fi
- if [ ${BUILD_DOCS} == 'true' ]; then pip install -q -r scale/pip/docs.txt -r scale/pip/production.txt; fi
script: 
- ./travis-build.sh
- ./push-docs.sh

branches:
  only:
  - master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/11ff4f6760c5e218ccb7
    on_success: change
    on_failure: always
    on_start: never
