language: python

python:
- '2.7'
env:
  matrix:
    - BUILD_DOCS='true'   RUN_TESTS='false'
    - BUILD_DOCS='false'  RUN_TESTS='true'

cache: pip

addons:
  postgresql: "9.4"

# Travis team suggested fix for truncated log build failures
filter_secrets: false

script: 
- ./travis-build.sh
- ./push-docs.sh

branches:
  only:
  - master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/11ff4f6760c5e218ccb7
    on_success: change
    on_failure: always
    on_start: never
