---
# nfs-server/tasks/main.yml
- name: Install dnsmasq
  tags: dns-server
  yum: name=dnsmasq
  become: true

- name: Configure dnsmaq
  tags: dns-server
  copy: src=forward.conf dest=/etc/dnsmasq.d/forward.conf
  become: true

- name: Start dnsmasq
  tags: dns-server
  service: state=started name=dnsmasq enabled=true
  become: true
