openapi: "3.0.0"
info:
  title: Batch Services
  version: v6
paths:
  /batches/:
    get:
      operationId: _rest_v6_batch_list
      summary: Batch List
      description: Returns a list of all batches
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: The page of the results to return. Defaults to 1.
        - in: query
          name: page_size
          schema:
            type: integer
          description: The size of the page to use for pagination of results. |
            Defaults to 100, and can be anywhere from 1-1000.
        - in: query
          name: started
          schema:
            type: string
            format: date-time
          description: The start of the time range to query
        - in: query
          name: ended
          schema:
            type: string
            format: date-time
          description: End of the time range to query, defaults to the current time
        - in: query
          name: recipe_type_id
          schema:
            type: integer
          description: Return only batches with a given recipe type identifier. |
            Duplicate it to filter by multiple values.
        - in: query
          name: is_creation_done
          schema:
            type: boolean
          description: Return only batches that match this value, indicating if the batch |
            has/has not finished creating its recipes
        - in: query
          name: is_superseded
          schema:
            type: boolean
          description: Return only batches that match this value, indicating if the batch |
              has/has not been superseded
        - in: query
          name: root_batch_id
          schema:
            type: integer
          description: Return only batches that belong to the chain with this root batch. |
            Duplicate it to filter by multiple values.
        - in: query
          name: order
          schema:
            type: string
          description: One or more fields to use when ordering the results. |
                       Duplicate it to multi-sort, (ex: order=host_name&order=created) |
                       Prefix fields with a dash to reverse the sort, (ex: order=-created)
      responses:
        '200':
          description: 200 response
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/batch_list'
    post:
      operationId: _rest_v6_batch_create
      summary: Job Type Post
      description: Creates or edits an existing job type
      requestBody:
        required: true
        content:
          application/json: 
            schema:
              $ref: '#/components/schemas/batch_post'
      responses:
        '201':
          description: The 201 CREATED response indicates a successful event
          headers:
            location:
              schema:
                type: string
              description: The url of the created batch
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/batch_detail'
                
  /job-types/{name}/:
    get:
      operationId: _rest_v6_job_type_versions
      summary: Job Type Versions
      description: Returns a list of the versions of a job type
      parameters:
        - in: path
          name: name
          schema:
            type: string
          description: name of an existing job type
        - in: query
          name: page
          schema:
            type: integer
          description: The page of the results to return. Defaults to 1.
        - in: query
          name: page_size
          schema:
            type: integer
          description: The size of the page to use for pagination of results.
            Defaults to 100, and can be anywhere from 1-1000.
        - in: query
          name: is_active
          schema:
            type: boolean
          description: if provided, only return names with a least one version that matches is_active
      responses:
        '200':
          description: 200 response
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/job_type_versions'
  /job-types/{name}/{version}/:
    get:
      operationId: _rest_v6_job_type_details
      summary: Job Type Details
      description: Returns detailed information about the job type with the specified name and version
      parameters:
        - in: path
          name: name
          schema:
            type: string
          description: name of an existing job type
        - in: path
          name: version
          schema:
            type: string
          description: version of an existing job type
      responses:
        '200':
          description: 200 response
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/job_type_detail'
    patch:
      operationId: _rest_v6_job_type_update
      summary: Job Type Update
      description: Update one or more fields in an existing job type
      requestBody:
        required: true
        content:
          application/json: 
            schema:
              $ref: '#/components/schemas/job_type_update'
      parameters:
        - in: path
          name: name
          schema:
            type: string
          description: name of an existing job type
        - in: path
          name: version
          schema:
            type: string
          description: version of an existing job type
      responses:
        '204':
          description: 204 no content
  /job-types/{name}/{version}/revisions/:
    get:
      operationId: _rest_v6_job_type_revisions
      summary: Job Type Revisions
      description: Returns a list of the revisions of a job type
      parameters:
        - in: path
          name: name
          schema:
            type: string
          description: name of an existing job type
        - in: path
          name: version
          schema:
            type: string
          description: version of an existing job type
        - in: query
          name: page
          schema:
            type: integer
          description: The page of the results to return. Defaults to 1.
        - in: query
          name: page_size
          schema:
            type: integer
          description: The size of the page to use for pagination of results.
            Defaults to 100, and can be anywhere from 1-1000.
      responses:
        '200':
          description: 200 response
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/job_type_revisions'
  /job-types/{name}/{version}/revisions/{revision_num}/:
    get:
      operationId: _rest_v6_job_type_revision_details
      summary: Job Type Revision Details
      description: Returns detailed information about the job type revision with the specified name, version and revision number
      parameters:
        - in: path
          name: name
          schema:
            type: string
          description: name of an existing job type
        - in: path
          name: version
          schema:
            type: string
          description: version of an existing job type
        - in: path
          name: revision_num
          schema:
            type: integer
          description: revision number of the job type
      responses:
        '200':
          description: 200 response
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/job_type_revision_detail'

  /batches/validation/:
    post:
      operationId: _rest_v6_job_type_validation
      summary: Job Type Validation
      description: Validates a job type without creating/editing it
      requestBody:
        required: true
        content:
          application/json: 
            schema:
              $ref: '#/components/schemas/job_type_validation_post'
      responses:
        '200':
          description: The 200 OK response indicates a successful event
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/job_type_validation'
components:
  schemas:
    batch_list:
      title: Batch List
      type: object
      properties:
        count:
          type: integer
          description: The total number of results that match the query parameters 
          example: 10
        next:
          type: string
          format: uri
          description: A URL to the next page of results.
          example: null
        previous:
          type: string
          format: uri
          description: A URL to the previous page of results.
          example: null
        results:
          type: array
          items:
            $ref: '#/components/schemas/batch'
          description: List of Batch objects

    batch_base:
      title: Batch Base
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: My Batch
        description:
          type: string
          example: My Batch Description 
        created:
          type: string
          format: date-time
          description: When the associated database model was initially created.
          example: 2015-09-10T15:24:53.503Z

    batch:
      title: Batch
      allOf:
        - ref: '#/components/schemas/batch_base'
        - type: object
          properties:
            recipe_type:
              $ref: '#/components/schemas/recipe_type_base'
              description: The recipe type that is associated with the batch  
            recipe_type_rev:
              $ref: '#/components/schemas/recipe_type_revision_base'
              description: The recipe type revision that is associated with the batch  
            event:
              $ref: '#/components/schemas/event_base'
              description: The trigger event that is associated with the batch  
            is_superseded:
              type: boolean
              description: Whether this batch has been replaced and is now obsolete.
            root_batch:
              $ref: '#/components/schemas/batch_base'
              description: The root batch for the chain that contains this batch, possibly null
            superseded_batch:
              $ref: '#/components/schemas/batch_base'
              description: The previous batch in the chain superseded by this batch, possibly null
            jobs_total:
              type: integer
              description: The total count of jobs within this recipe
              example: 1
            jobs_pending:
              type: integer
              description: The count of PENDING jobs within this recipe
              example: 1
            jobs_blocked:
              type: integer
              description: The count of BLOCKED jobs within this recipe
              example: 1
            jobs_queued:
              type: integer
              description: The count of QUEUED jobs within this recipe
              example: 1
            jobs_running:
              type: integer
              description: The count of RUNNING jobs within this recipe
              example: 1
            jobs_failed:
              type: integer
              description: The count of FAILED jobs within this recipe
              example: 1
            jobs_completed:
              type: integer
              description: The count of COMPLETED jobs within this recipe
              example: 1
            jobs_canceled:
              type: integer
              description: The count of CANCELED jobs within this recipe
              example: 1
            recipes_estimated:
              type: integer
              description: The estimated count of recipes (including sub-recipes) that will be created |
                for this batch
              example: 1
            recipes_total:
              type: integer
              description: The total count of recipes (including sub-recipes) within this batch
              example: 1
            sub_recipes_completed:
              type: integer
              description: The count of completed recipes (including sub-recipes) within this batch 
              example: 1
            superseded:
              type: string
              format: date-time
              description: When the the batch became superseded by another batch.
              example: 2015-09-10T15:24:53.987Z
            last_modified:
              type: string
              format: date-time
              description: When the associated database model was last saved.
              example: 2015-09-10T15:24:53.987Z

    batch_details:
      title: Batch Details
      allOf:
        - ref: '#/components/schemas/batch'
        - type: object
          properties:
            recipe_type_rev:
              $ref: '#/components/schemas/recipe_type_revision'
              description: The recipe type revision that is associated with the batch  
            event:
              $ref: '#/components/schemas/event_details'
              description: The trigger event that is associated with the batch  
            definition:
              $ref: '#/components/schemas/batch_definition'
              description: The definition of the batch    
            configuration:
              $ref: '#/components/schemas/batch_config'
              description: The configuration of the batch           
            job_metrics:
              $ref: '#/components/schemas/job_metrics'
              description: The metrics for each top level recipe job (not in a sub-recipe) in the batch. |
                Each recipe job name maps to the metrics for that job. The job count metrics |
                (e.g. jobs_total) are similar to the top level batch metrics. The duration |
                metrics (e.g. min_seed_duration) detail the minimum, average, and maximum |
                durations for completing the Seed run and completing the overall Scale job. |
                The durations are provided in the ISO-8601 duration format.

    batch_definition:
      title: Batch Definition
      type: object
      properties:
        previous_batch:
          $ref: '#/components/schemas/previous_batch_definition'
          description: Indicates that the batch should re-process the recipes from a |
            previous batch. This will link the previous and new batch together |
            so that their metrics can be easily compared. The previous batch |
            must have the same recipe type as the new batch and must have |
            finished creating all of its recipes.

    previous_batch_definition:
      title: Batch Definition
      type: object
      required: [root_batch_id]
      properties:
        root_batch_id:
          type: integer
          description: The root batch ID of the previous batch. Scale will find the last |
            (non-superseded) batch with this root ID and it will be reprocessed by this batch.
          example: 4
        forced_nodes:
          $ref: '#/components/schemas/forced_nodes'
          description:  A forced nodes JSON object that defines the batch recipe nodes to |
            force to re-process even if there are no changes to them.
      
    job_type_validation_post:
      title: Job Type Validation Post
      type: object
      properties:      
        # Commenting out until added
        # manifest:
        #   $ref: '#/components/schemas/seed_manifest'
        configuration:
          $ref: '#/components/schemas/job_type_config'
      required:
      - manifest
      
    job_type_validation:
      title: Job Type Validation
      type: object
      properties:
        is_valid:
          type: boolean
          description: The job type is valid
          example: true
        validation_error:
          type: array
          items:
            $ref: '#/components/schemas/validation_error'
        validation_warning:
          type: array
          items:
            $ref: '#/components/schemas/validation_warning'