openapi: "3.0.0"
info:
  title: Diagnostic Services
  version: v6
paths:
  /diagnostics/job/bake/:
    post:
      tags:
        - Diagnostic Services
      operationId: _rest_v6_queue_scale_bake_jobs
      summary: Queue Scale Bake Jobs
      description: Creates and queues a specified number of Scale Bake jobs. Scale Bake jobs wait for 15 minutes and then complete,
        allowing a simulation of jobs that take some amount of time to complete.  
      requestBody:
        required: true
        content:
          application/json: 
            schema:
              $ref: '#/components/schemas/number'
      responses:
        '202':
          description: OK - accepted
            
  /diagnostics/recipe/casino/:
    post:
      tags:
        - Diagnostic Services
      operationId: _rest_v6_queue_scale_casino_recipies
      summary: Queue Scale Casino Recipies
      description: Creates and queues a specified number of Scale Casino recipes. Scale Casino recipes are useful for testing recipes in
        the presence of job failures.   
      requestBody:
        required: true
        content:
          application/json: 
            schema:
              $ref: '#/components/schemas/number'
      responses:
        '202':
          description: OK - accepted
            
  /diagnostics/job/hello/:
    post:
      tags:
        - Diagnostic Services
      operationId: _rest_v6_queue_scale_hello_jobs
      summary: Queue Scale Hello Jobs
      description: Creates and queues a specified number of Scale Hello jobs. Scale Hello jobs simply print out a hello message and are
        useful for testing and evaluating Scale's job throughput performance.  
      requestBody:
        required: true
        content:
          application/json: 
            schema:
              $ref: '#/components/schemas/number'
      responses:
        '202':
          description: OK - accepted
            
  /diagnostics/job/roulette/:
    post:
      tags:
        - Diagnostic Services
      operationId: _rest_v6_queue_scale_roulette_jobs
      summary: Queue Scale Roulette Jobs
      description: Creates and queues a specified number of Scale Roulette jobs. Scale Roulette randomly complete/fail with 50% odds and
        are useful for testing jobs that both complete and fail.  
      requestBody:
        required: true
        content:
          application/json: 
            schema:
              $ref: '#/components/schemas/number'
      responses:
        '202':
          description: OK - accepted
            
components:
  schemas:
    number:
      title: Number
      type: object
      properties:
        num:
          type: integer
          description: Number of jobs to queues
          example: 100