openapi: "3.0.0"
info:
  title: Ingest Services
  version: v6
paths:
  /v6/ingests:
    get:
      operationId: _rest_v6_ingest_list
      summary: Ingest List
      description: Returns a list of all ingests
      parameters:
        -in: query
          name: page
          schema:
            type: integer
          description: The page of the results to return. Defaults to 1.
        -in: query
          name: page_size
          schema:
            type: integer
          description: The size of the page to use for pagination of results. |
            Defaults to 100, and can be anywhere from 1-1000.
        -in: query
          name: started
          schema:
            type: string
            format: date-time
          description: The start of the time range to query
        -in: query
          name: ended
          schema:
            type: string
            format: date-time
          description: End of the time range to query, defaults to the current time
        -in: query
          name: order
          schema:
            type: string
          description: One or more fields to use when ordering the results. |
            Duplicate it to multi-sort, (ex: order=host_name&order=created) |
            Nested objects require a delimiter (ex: order=source_file__created)
            Prefix fields with a dash to reverse the sort, (ex: order=-created)
        -in: query
          name: status
          schema:
            type: string
          description: Return only ingests with a status matching this string. |
            Choices: [TRANSFERRING, TRANSFERRED, DEFERRED, INGESTING, INGESTED, ERRORED, DUPLICATE]
        -in: query
          name: scan_id
          schema:
            type: integer
          description: Return only ingests created by a given scan process identifier. |
            Duplicate it to filter by multiple values.
        -in: query
          name: strike_id
          schema:
            type: integer
          description: Return only ingests created by a given strike process identifier. |
            Duplicate it to filter by multiple values.
        -in: query
          name: file_name
          schema:
            type: string
          description: Return only ingests with a specific file name. 
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ingest_list'
  /v6/ingests/{id}/:
    get:
      operationId: _rest_v6_ingest_details
      summary: Ingest Details
      description: Returns a specific ingest and all its related model information
      parameters:
        -in: path
          name: id
          schema:
            type: integer
          description: id of an existing node
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ingest_details'
 /v6/ingests/status/:
    get:
      operationId: _rest_v6_ingest_status
      summary: Ingest Status
      description: Returns status summary information (counts, file sizes) for completed ingests grouped into 1 hour time slots. |
        NOTE: Time range must be within a one month period (31 days).
      parameters:
        -in: query
          name: page
          schema:
            type: integer
          description: The page of the results to return. Defaults to 1.
        -in: query
          name: page_size
          schema:
            type: integer
          description: The size of the page to use for pagination of results. |
            Defaults to 100, and can be anywhere from 1-1000.
        -in: query
          name: started
          schema:
            type: string
            format: date-time
          description: The start of the time range to query
        -in: query
          name: ended
          schema:
            type: string
            format: date-time
          description: End of the time range to query, defaults to the current time
        -in: query
          name: use_ingest_time
          schema:
            type: boolean
          description: Whether to group counts by ingest time or data time. |
            Ingest time is when the strike process registered the file. |
            Data time is the time when the data was collected by a sensor. |
            Defaults to False (data time).  
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ingest_status'

components:
  schemas:
    ingest_list:
      title: Ingest List
      type: object
      properties:
        count:
          type: integer
          description: The total number of results that match the query parameters 
          example: 10
        next:
          type: string
          format: uri
          description: A URL to the next page of results.
          example: null
        previous:
          type: string
          format: uri
          description: A URL to the previous page of results.
          example: null
        results:
          type: array
          items:
            $ref: '#/components/schemas/ingest_details'
          description: List of ingest objects
    ingest_details:
      title: Ingest Details
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier of the model. Can be passed to the details API call 
          example: 4
        file_name:
          type: string
          description: The name of the file being ingested.  
          example: file_name.txt
        scan:
          $ref: '#/components/schemas/scan'
        strike:
          $ref: '#/components/schemas/strike'
        is_active:
          type: string
          description: True if the node is actively participating in the cluster.
          example: True
        deprecated:
          type: string
          format: date-time
          description: When the node was removed (is_active == False) from the cluster.
        created:
          type: string
          format: date-time
          description: When the associated database model was initially created.
        last_modified:
          type: string
          format: date-time
          description: When the associated database model was last saved.
    node_update:
      title: Node Update
      type: object
      properties:
        pause_reason:
          type: string
          description: The reason this node is paused if is_paused is true. |
            This is a descriptive field for presentation to the user
          example: Node is undergoing scheduled maintenance
        is_paused:
          type: boolean
          description: True if the node is paused and will not accept new jobs for execution. |
            Remaining tasks for a previously executing job will complete.
          example: False
        is_active:
          type: string
          description: True if the node is actively participating in the cluster.
          example: True