openapi: "3.0.0"
info:
  title: Scale File Services
  version: v5

paths:
  /files/:
    get:
      tags:
        - Scale File Services
      summary: Files
      description: Returns detailed information about files associated with Scale.
      parameters:
        - in: query
          name: started
          schema:
            type: string
            format: date-time
          description: The start of the time range to query
        - in: query
          name: ended
          schema:
            type: string
            format: date-time
          description: End of the time range to query, defaults to the current time
        - in: query
          name: time_field
          schema:
            type: string
            enum:
              - last_modified
              - data
              - source
            default: last_modified
          description: Indicates the time field(s) that *started* and *ended* will use for
            time filtering.
        - in: query
          name: file_name
          schema:
            type: string
          description: Return only files with a given file name.
      responses:
        '200':
          description: OK - indicates a successful event
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/scale_file_list'

components:
  schemas:
    scale_file_list:
      title: Scale File List
      type: object
      properties:
        count:
          type: integer
          description: The total number of results that match the query parameters 
          example: 10
        next:
          type: string
          format: uri
          description: A URL to the next page of results.
          example: null
        previous:
          type: string
          format: uri
          description: A URL to the previous page of results.
          example: null
        results:
          type: array
          items:
            $ref: '#/components/schemas/scale_file'
          description: List of Scale files

    scale_file:
      title: Product File
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier of the model. Can be passed to the details API call 
          example: 4
        workspace:
          $ref: '#/components/schemas/workspace_base'
        file_name:
          type: string
          description: The name of the source file.
          example: my_file.kml
        media_type:
          type: string
          description: The IANA media type of the product file.
          example: application/vnd.google-earth.kml+xml
        file_type:
          type: string
          description: The file type of the product
          example: PRODUCT
        file_size:
          type: integer
          description: The size of the file in bytes.  
          example: 1234
        data_type:
          type: array
          items:
            type: string  
          description: A list of string data type "tags" for the file.
        is_deleted:
          type: boolean
          description: Whether the source file has been deleted.
          example: True
        uuid:
          type: string
          format: uri
          description: A unique identifier that stays stable across multiple job execution runs.
          example: c8928d9183fc99122948e7840ec9a0fd
        url:
          type: string
          format: uri
          description: The absolute URL to use for downloading the file.
          example: http://host.com/file/path/my_file.kml
        created:
          type: string
          format: date-time
          description: When the associated database model was initially created.
          example: 2015-09-10T15:24:53.503Z
        deleted:
          type: string
          format: date-time
          description: When the source file was deleted.
          example: 2015-09-10T15:24:53.987Z
        data_started:
          type: string
          format: date-time
          description: The start time of the source data being ingested.
          example: 2015-09-10T15:24:53.503Z
        data_ended:
          type: string
          format: date-time
          description: The ended time of the source data being ingested.
          example: 2015-09-10T15:24:53.987Z
        geometry:
          type: string
          description: The full geospatial geometry footprint of the source file. (WKT format)
          example: POLYGON((11 -11,22 -22,33 -33,44 -44))
        center_point:
          type: string
          description: The central geospatial location of the source file.
          example: POINT(11 -11)
        countries:
          type: array
          items:
            type: string  
          description: A list of zero or more strings with the ISO3 country codes for countries
            contained in the geographic boundary of this file.
        last_modified:
          type: string
          format: date-time
          description: When the associated database model was last saved.
          example: 2015-09-10T15:24:53.987Z
        source_started:
          type: string
          format: date-time
          description: When collection of the underlying source file started. 
          example: 2015-09-10T15:24:53.987Z
        source_ended:
          type: string
          format: date-time
          description: When collection of the underlying source file ended. 
          example: 2015-09-10T15:24:53.987Z
        file_path:
          type: string
          description: The path to the file.
          example: '/path/to/file.kml'