---
# scale-scheduler/tasks/main.yml
# work around a bug
- name: Pull image
  command: 'docker pull {{ docker_registry }}scale:{{ scale_docker_version }}'
  become: true

- name: migrate db changes
  tags: scale-scheduler
  docker:
    docker_api_version: '{{ docker_api_version }}'
    image: '{{ docker_registry }}scale:{{ scale_docker_version }}'
    state: started
    tty: true
    command: 'migrate --noinput'
    volumes:
      - '/etc/scale/local_settings.py:/opt/scale/scale/local_settings.py'
  become: true
  notify:
    - restart scheduler
