---
# db-init/tasks/main.yml
# work around a bug
- name: Pull image
  command: 'docker pull {{ docker_registry }}postgres'
  become: true

- name: Wait for the postgis database to initialize itself
  tags: db-init
  wait_for: port='{{ db_port }}' host='{{ db_host }}' delay=10

- name: Initialize postgres database
  tags: db-init
  docker:
    docker_api_version: '{{ docker_api_version }}'
    image: '{{ docker_registry }}postgres'
    state: started
    tty: true
    detach: no
    env:
      'PGPASSWORD': '{{ db_password }}'
    command: sh -c 'createdb -h {{ db_host }} -U {{ db_username }} -T template_postgis {{ db_name }}'
  become: true
