---
# vagrant.yml
# site file for vagrant cluster
- include: mesos.yml

- hosts: db
  roles:
    - postgis
    - db-init

- hosts: scale-framework
  roles:
    - docker-registry
    - nfs-server

- hosts: scale-framework
  roles:
    - build-scale

- hosts: scale-framework
  roles:
    - load-initial-data
    - init-examples

- include: scale.yml
