---
# vagrant.yml
# site file for vagrant cluster
- include: mesos.yml

- hosts: db
  roles:
    - postgis
    - db-init

- hosts: scale-framework
  roles:
    - build-scale

- include: scale.yml

- hosts: scale-framework
  roles:
    - load-initial-data
