---
# init-examples/tasks/main.yml
- name: Install initialization script
  tags: init-examples
  copy: src=example_data.json dest=/tmp/example_data.json

- name: Initialize example database
  tags: init-examples
  django_manage: command=loaddata app_path='{{ django_build_dir }}' fixtures=/tmp/example_data.json

- name: Build landsat-parse docker image
  tags: init-examples
  docker_image:
    path: "/scale/dockerfiles/examples/landsat-parse"
    name: "landsat-parse_1.0"
    tag: "dev"
    state: build
  become: true
  notify:
    - push landsat-parse
